#!/usr/bin/env python3
"""
Turn an X11 misc-fixed bitmap font into picosdl's glyph table.

Run once, by hand; the output is committed. picosdl's build must not need Python,
FreeType or a font installed, so this is not wired into CMake - it is here so the
table can be regenerated or a different size chosen without reverse-engineering
the format.

    ./tools/make-font.py /usr/share/fonts/X11/misc/9x15.pcf.gz 15 9 > src/psdl_font9x14.inc

Source fonts: the X11 misc-fixed family (6x13, 7x14, 8x13, 9x15, 10x20 and the
rest), whose COPYING in font-misc-misc reads in full "Public domain font. Share
and enjoy."

Format: one glyph per printable ASCII code 0x20..0x7E, column-major, one uint16
per column with bit 0 the top row. Same convention as the 5x7 table next to it,
widened because 14 rows do not fit in a byte.

The cell height is measured rather than assumed: misc-fixed 9x15 puts its ink in
14 of its 15 rows, so the blank row is dropped and the glyphs are 9x14.
"""
import gzip
import os
import shutil
import sys
import tempfile
from PIL import Image, ImageDraw, ImageFont

def main(path, px, width):
    first, last = 0x20, 0x7E
    chars = "".join(chr(c) for c in range(first, last + 1))
    n = len(chars)

    # FreeType reads PCF but not PCF.GZ, and the installed fonts are gzipped.
    tmp = None
    if path.endswith(".gz"):
        tmp = tempfile.NamedTemporaryFile(suffix=".pcf", delete=False)
        with gzip.open(path, "rb") as z:
            shutil.copyfileobj(z, tmp)
        tmp.close()
        font = ImageFont.truetype(tmp.name, px)
    else:
        font = ImageFont.truetype(path, px)

    # One string, one baseline: slicing a strip on the pitch cannot drift the way
    # rendering each glyph on its own can.
    img = Image.new("L", (width * n, px * 3), 0)
    ImageDraw.Draw(img).text((0, px), chars, font=font, fill=255)
    p = img.load()

    ink = [(x, y) for y in range(img.height) for x in range(img.width) if p[x, y] > 127]
    if not ink:
        sys.exit("no ink: wrong pixel size for this font?")
    y0 = min(y for _, y in ink)
    y1 = max(y for _, y in ink)
    height = y1 - y0 + 1
    if len({p[x, y] for x, y in ink}) != 1:
        sys.exit("antialiased output: this is not a bitmap font")
    if height > 16:
        sys.exit(f"{height} rows will not fit in a uint16 column")

    name = f"{width}x{height}"
    print(f"/*")
    print(f" * A {name} bitmap font, generated by tools/make-font.py from")
    print(f" * {path} - one of the X11 misc-fixed fonts, whose licence")
    print(f' * reads in full: "Public domain font.  Share and enjoy."')
    print(f" *")
    print(f" * Do not edit. Column-major, one uint16 per column, bit 0 the top row.")
    print(f" */")
    print(f"#define PSDL_FONT{width}X{height}_WIDTH   {width}")
    print(f"#define PSDL_FONT{width}X{height}_HEIGHT  {height}")
    print(f"#define PSDL_FONT{width}X{height}_ADVANCE {width}")
    print()
    print(f"static const Uint16 font{width}x{height}_glyphs[{n}][{width}] = {{")
    for i, ch in enumerate(chars):
        cols = []
        for cx in range(width):
            bits = 0
            for ry in range(height):
                if p[i * width + cx, y0 + ry] > 127:
                    bits |= 1 << ry
            cols.append(bits)
        label = {0x20: "space", 0x5C: "backslash"}.get(ord(ch), ch)
        print("\t{" + ",".join(f"0x{c:04X}" for c in cols) + f"}}, /* {label} */")
    print("};")

    if tmp:
        os.unlink(tmp.name)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]))
